DROP TABLE IF EXISTS quizzes CASCADE;
DROP TABLE IF EXISTS questions CASCADE;

CREATE TABLE quizzes (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL
  );

CREATE TABLE questions (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  question TEXT NOT NULL,
  correct_answer TEXT NOT NULL,
  incorrect_answers VARCHAR(250) NOT NULL,
  owner_id BIGINT NOT NULL REFERENCES quizzes(id)
);